services:
  starter:
    image: starter
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
      PORT: 3000
    ports:
      - 3000:3000
      - 9229:9229
    command: ["npm", "run", "dev:debug"]
